export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_BY_CONTINENT = 'GET_BY_CONTINENT';
export const ORDER_COUNTRIES = 'ORDER_COUNTRIES';
export const GET_NAME_COUNTRIES = 'GET_NAME_COUNTRIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ORDER_ACTIVITY = 'ORDER_ACTIVITY';
export const GET_DETAIL = 'GET_DETAIL';
export const POST_ACTIVITY = 'POST_ACTIVITY';

